### ISSUE TITLE
Entering a long line (> 40 cols) in 40 col mode produces syntax error

### ISSUE THREAD

**Issue by fachat** [sjgray/cbm-edit-rom#12]
I was entering a long line of direct BASIC input (i.e. across two screen lines) and the line was not executed, but gave a SYNTAX ERROR.

ROM definition is from https://github.com/fachat/MicroPET/blob/main/ROM/edit40gx.asm
LIne entered was:
FORI=0TO255:POKE32768+I,I:POKE32768+2048+I,I:NEXT

The same line on an original BASIC4 editor worked. A shorter line (<40cols) worked on the custom editor ROM also. 

My assumption is that the linked line handling somehow got broken.

**Comment by sjgray** [comment]
If you are using codebase 1 there is no line linking. See my webpage for more info. If possible (see features chart) use codebase 0, which does have line linking. I have started working on adding more features to C0 but they are not complete yet.
