### ISSUE TITLE
crtc-8296D-80-50hz-old.asm missing?

### ISSUE THREAD

**Issue by arttu76** [sjgray/cbm-edit-rom#17]
Sorry for the hassle, this is probably just a stupid user error but I just bought and repaired a dead 8296 with QWERTZ keyboard (50Hz power) and was in process of patching it to use QWERTY keyboard.

I edited edit.asm to use codebase 2, din keyboard, PAL refresh, 80 columns, 50Hz line freq and no external features.

When running the project on my Linux machine (don't have windows so I have to use wine) I get the error:
$ wine acme -r editrom.txt editrom.asm
Error - File editrom82.asm, line 1393 (Zone <untitled>): Cannot open input file.

Checking while file that is reveals:
$ cat -n editrom82.asm | grep 1393
  1393	!SOURCE "crtc-8296D-80-50hz-old.asm"

The repo doesn't seem to contain this crtc-8296D-80-50hz-old.asm ... or am I just doing something stupid (=the most probable reason) ?

**Comment by sjgray** [comment]
Sorry, looks like that file got removed and renamed. There is "crtc-80-50hz-8296D-old.asm" in the removed folder. You can try copying this file to the main folder and renaming it back to "crtc-8296D-80-50hz-old.asm" or editing the filename in the !SOURCE line. If that doesn't work perhaps use CODEBASE1 instead of 2 unless you specifically need the extra diacritics support or the extra screen editing stuff.

**Comment by arttu76** [comment]
Ok thanks! At least it completes and creates the binary - I'll have to dig out my eprom programmer and check the rom on the PET.

And thanks for the tip about using CODEBASE1.

**Comment by arttu76** [comment]
OK created the ROM and it works okay!

I noticed that if I build (with CODEBASE=1 and) with SS40=1, it causes incompatibilities. For example Trekwar-game does not work. Also the 40-column switcher "cbm4032v2.1 50hz.prg" crashes with SS40=1.

**Comment by sjgray** [comment]
My project moves some code, so certain apps that call directly into the editor rom may fail. The 4032 program is one that does. If you search the source code you can see a note where the 4032 jumps into.
I have not tried the Trekwar game.
Steve


    On Thursday, July 7, 2022 at 04:54:13 p.m. EDT, Arttu Ylärakkola ***@***.***> wrote:  
 
 


OK created the ROM and it works okay!

I noticed that if I build (with CODEBASE=1 and) with SS40=1, it causes incompatibilities. For example Trekwar-game does not work. Also the 40-column switcher "cbm4032v2.1 50hz.prg" crashes with SS40=1.
